import pandas as pd
df=pd.read_csv("data/cleaned_sales.csv")
print("Columns:")
print(df.columns)
print("\nNumeric Columns:")
print(df.select_dtypes(include="number").columns)
print("/nNumeric Summary:")
print(df[["Quantity","Unit_Price","Discount","Sales"]].describe())
print("\nTotal Sales:")
print(df["Sales"].sum())
print("\nAverage Sales:")
print(df["Sales"].mean())
print("\nTotal Quantity:")
print(df["Quantity"].sum())
print("\nRegion-wise Sales:")
print(df.groupby("Region")["Sales"].sum().sort_values(ascending=False))
print("\ncategory-wise Sales:")
print(df.groupby("Category")["Sales"].sum().sort_values(ascending=False))
print("\nTop 10 Products By Sales: ")
print(df.groupby("Product")["Sales"].sum().sort_values(ascending=False).head(10))
print("\nDiscount-wise Sales:")
print(df.groupby("Discount")["Sales"].agg(["sum","mean","count"]).sort_index())
print("\nRegion and Category-wise Sales:")
print(df.groupby(["Region","Category"])["Sales"].sum().sort_values(ascending=False))
print("\ncorrelation:")
print(df[["Quantity","Unit_Price","Discount","Sales"]].corr())
print("\nHighest Sales Order:")
print(df.loc[df["Sales"].idxmax()])
print("\nLowest Sales Order:")
print(df.loc[df["Sales"].idxmin()])
print("\nAnalysis Completed Successfully!")